wget -O logo/bezirkfk.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-bezirkfk.png
wget -O logo/berlin.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-berlin.png
wget -O logo/kuturstift-bund.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-kuturstift-bund.png
wget -O logo/hkf.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-hkf.png
wget -O logo/mercatorstiftung_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-mercatorstiftung_01.png
wget -O logo/dklb.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-dklb.png
wget -O logo/foerderband.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-foerderband.png
wget -O logo/auswaertigesamt.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-auswaertigesamt.png
wget -O logo/berlinerprojektfonds-kb.gif http://old.ballhausnaunynstrasse.de/uploads/pics/logo-berlinerprojektfonds-kb.gif
wget -O logo/fondsdakue_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-fondsdakue_01.png
wget -O logo/fondssoziokultur.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-fondssoziokultur.png
wget -O logo/pcwstiftung.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-pcwstiftung.png
wget -O logo/schering.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-schering.png
wget -O logo/ruhrtriennale.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ruhrtriennale.png
wget -O logo/garajistanbul_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-garajistanbul_01.png
wget -O logo/britishcouncil_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-britishcouncil_01.png
wget -O logo/ps122-ny.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ps122-ny.png
wget -O logo/9thspace-ny.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-9thspace-ny.png
wget -O logo/generalkonsulat-ny_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-generalkonsulat-ny_01.png
wget -O logo/deutscheshaus-ny.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-deutscheshaus-ny.png
wget -O logo/ernstreuter_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ernstreuter_01.png
wget -O logo/ngbk_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ngbk_01.png
wget -O logo/daimelerfs_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-daimelerfs_01.png
wget -O logo/hebbel_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-hebbel_01.png
wget -O logo/goethe-istanbul.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-goethe-istanbul.png
wget -O logo/senatsverwalt_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-senatsverwalt_01.png
wget -O logo/kulturprojekte_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-kulturprojekte_01.png
wget -O logo/kunstraum_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-kunstraum_01.png
wget -O logo/berlinistanbul2009_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-berlinistanbul2009_01.png
wget -O logo/botschaftfranz_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-botschaftfranz_01.png
wget -O logo/boellstiftung_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-boellstiftung_01.png
wget -O logo/conflictzone_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-conflictzone_01.png
wget -O logo/billetix_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-billetix_01.png
wget -O logo/baalnovo_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-baalnovo_01.png
wget -O logo/medienboard_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-medienboard_01.png
wget -O logo/berlinerunterwelt_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-berlinerunterwelt_01.png
wget -O logo/suntop_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-suntop_01.png
wget -O logo/diyalogtheater_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-diyalogtheater_01.png
wget -O logo/gehttoistanbul_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-gehttoistanbul_01.png
wget -O logo/ietm_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ietm_01.png
wget -O logo/ifa_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ifa_01.png
wget -O logo/iksv_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-iksv_01.png
wget -O logo/istanbulmodern_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-istanbulmodern_01.png
wget -O logo/langenacht_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-langenacht_01.png
wget -O logo/merhaba_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-merhaba_01.png
wget -O logo/mpool_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-mpool_01.png
wget -O logo/sanartfilm_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-sanartfilm_01.png
wget -O logo/thy_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-thy_01.png
wget -O logo/tuerkfilmwoche_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-tuerkfilmwoche_01.png
wget -O logo/ankafilm.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-ankafilm.png
wget -O logo/augustbebel.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-augustbebel.png
wget -O logo/reservix.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-reservix.png
wget -O logo/stpoelten.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-stpoelten.png
wget -O logo/taz_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-taz_01.png
wget -O logo/zitty_01.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-zitty_01.png
wget -O logo/dinamix.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-dinamix.png
wget -O logo/fluxfm.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-fluxfm.png
wget -O logo/metropolfm.png http://old.ballhausnaunynstrasse.de/uploads/pics/logo-metropolfm.png
